// TODO: Create a function to generate markdown for README
const generateMarkdown = (answers) =>
`#<h1 align="center">${answers.title}</h1>

![badge](https://img.shields.io/badge/license-${answers.license}-blue)](https://shields.io)

## Description<br/>
${answers.description}<br/>

## Table of Contents<br/>
- [Description](#description)<br/>
- [Installation](#installation)<br/>
- [Usage](#usage)<br/>
- [License](#license)<br/>
- [Contributing](#contributing)<br/>
- [Tests](#tests)<br/>
- [Questions](#questions)<br/>

## Installation<br/>
${answers.installation}<br/>

## Usage<br/>
${answers.usage}<br/>

## License<br/>
![badge](https://img.shields.io/badge/license-${answers.license}-brightgreen)
<br/>
This application is covered by the ${answers.license} license.
<br/>

## Contributing<br/>
${answers.contributing}<br/>

## Tests<br/>
${answers.tests}<br/>

## Questions<br/>
${answers.questions}<br/>

Find me on GitHub: [${answers.username}](https://github.com/${answers.username})<br/>

Email me with any questions: ${answers.email}<br/>
This README was generated by README GENERATOR`;

module.exports = generateMarkdown;